name: Test
on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        default: "3.9"
        type: string

jobs:

  python-test:
    name: Run Pytest
    runs-on: ubuntu-latest
    steps:

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: ./.github/actions/python-setup
        with:
          PYTHON_VERSION: ${{ inputs.PYTHON_VERSION }}

      - name: Set Test Environment Variables
        run: |
          cat .env.template >> .env 

      - name: Pytest
        run: poetry run pytest -v --cov app

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: .coverage
