name: Test
on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        default: "3.9"
        type: string

jobs:
  python-test:
    name: Run Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: ./.github/actions/python-setup
        with:
          PYTHON_VERSION: ${{ inputs.PYTHON_VERSION }}

      - name: Set Test Environment Variables
        run: |
          cat .env.template >> .env

      - name: Pytest
        env:
          ENV: "test"
          DETA_SPACE_APP_HOSTNAME: "http://127.0.0.1:8000"
          DATABASE_TYPE: ${{ secrets.TEST_DETA_DATABASE_TYPE }}
          DETA_PROJECT_KEY: ${{ secrets.TEST_DETA_PROJECT_KEY }}
        run: poetry run pytest -v --cov app --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
