name: Main Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml
    with:
      ENFORCE_BLACK: "true"
      ENFORCE_PYRIGHT: "true"
      ENFORCE_BANDIT: "true"
      ENFORCE_FLAKE8: "true"
    secrets: inherit

  test:
    name: Test
    uses: ./.github/workflows/test.yaml
    needs: lint
    secrets: inherit

  deploy-dev:
    name: Deploy Development
    if: success()
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: development
    needs: test
    secrets: inherit

  deploy:
    name: Deploy Production
    if: success() && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: production
    needs: deploy-dev
    secrets: inherit
